[workspace]
members = [
	"consensus",
	"message-broker",
	"network",
	"parachain-upgrade",
	"primitives",
	"runtime",
	"test/runtime",
	"test/client",
	"test/parachain/runtime",
	"test/parachain/",
	"upward-message",
]

exclude = ["vendor"]

[profile.release]
panic = 'unwind'
